dist: trusty
sudo: false
language: node_js
node_js:
  - "node"
python:
  - "3.6.1"
cache:
  directories:
    - "node_modules"
services:
  - redis-server
install:
  - chmod +x redis_database.sh
  - ./redis_database.sh
  - npm i && cd client && npm i && cd ..
  - cd client && npm run build && cd ..
  
  - python3.6 -m pip install requests
script: 
  - npm start &
  - sleep 2
  - python3.6 test/test_pending.py
  - python3.6 test/test_quotes.py
  - python3.6 test/test_random.py
  
after-script:
  - sleep 5
  - killall node
