dist: trusty
sudo: enabled
language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
install:
  - npm i && cd client && npm i && cd ..
  - cd client && npm run build && cd ..
  - chmod +x redis_quickstart.sh
  - sudo ./redis_quickstart.sh
script: 
  - npm start &
after-script:
  - killall node
